### ISSUE TITLE
Unable to import library without a DB running

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/PDS-Pipelines#386] opened 2020-03-23 21:23 UTC
It looks like someone put in logic that should allow for the import of a module in pds_pipelines without a DB. Looking in db.py it looks like the original intent was to attempt to create a connection and if the creation failed to return None, None. I think this is the case because lines [17-18](https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/pds_pipelines/db.py#L17) are setting the variables to default to None.

It looks like the later modified such at the config has defaults inside the library. This makes is so that the try will never fail. If the try never fails, then the check to see if a valid session is returned in [models/upc_models.py](https://github.com/USGS-Astrogeology/PDS-Pipelines/blob/master/pds_pipelines/models/upc_models.py#L156) always returns a valid session object, even if no DB exists.

So the scaffolding is there to not need a DB to even import, but it looks like this has been slowly (and unintentionally) modified away.

**Comment by AustinSanders** [comment] 2021-01-08 20:45
This issue is _technically_ addressed in #520, but we recognize that a lot of the motivation behind the issue is still not addressed.  In other words, while the library can be imported without an active DB after #520, some of the code will still fail due to inherent coupling between the processing and the database queries.

We've identified several steps necessary to better address the motivation behind this issue:

1. Keep working on decomposing the code into more modular units / functions (#469)
2. Decouple the processing / database units
3. Provide branching logic or try/except logic to navigate the portions dealing with the database.

**Closed** 2021-01-11 21:03 UTC
Labels: bug
